name: Bug report
description: 'Something doesn''t seem correct and it might be a bug '
title: '[Bug]: '
assignees:
  - kikugie
labels:
  - bug
body:
  - type: dropdown
    id: loader
    attributes:
      label: Mod loader
      description: Which mod loader are you using?
      options:
        - Fabric
        - Forge
        - Quilt
        - NeoForge
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft version
      description: Which Minecraft version are you playing on?
      placeholder: 1.20.4
    validations:
      required: true
  - type: input
    id: et_version
    attributes:
      label: Mod version
      description: >-
        Which version of Elytra Trims (and Extensions if applicably) are you using?
      placeholder: 2.0.0
    validations:
      required: true
  - type: checkboxes
    id: mods
    attributes:
      label: Affected mods
      description: |
        Which mods does the issue affect. 
        Extensions is responsible for textures for trims from other mods, such as More Armor Trims and Geode+.
        Everything else is for Elytra Trims to blame.
      options:
        - label: Elytra Trims
          required: false
        - label: Extensions
          required: false
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: >-
        Elytra Trims crashes on startup with OptiFabric installed, but doesn't with Sodium.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >-
        Required steps to reproduce the bug. When reproducing the bug try to
        minimise used mods. It will be much easier to figure out the problem if
        you don't have 100 mods in your log.
      placeholder: |
        1. Install OptiFabric, Fabric API and Elytra Trims 
        2. Launch the game 
        3. Crash
  - type: input
    id: logs
    attributes:
      label: Relevant logs
      description: |
        If it's a crash, send the corresponding Minecraft log from the `logs`
        folder here.         
        Please upload the log file as an attachment, or upload the log to [pastebin](https://pastebin.com/) / [mclo.gs](https://mclo.gs/) and paste the url here.  
        Leave empty if there is none.
      placeholder: https://mclo.gs/...
