name: Mod compatibility
description: Report features incorrectly working in combination with other mods
labels: [compatibility]
body:
  - type: markdown
    attributes:
      value: Report only features working incorrectly. If your game crashes in combination with the other mod, please open a bug report.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Trims rendering on elytras with mod A.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: No trims are rendered.
  - type: textarea
    id: mod-links
    attributes:
      label: Mod links
      description: Link mods where this issue occurs
      placeholder: https://modrinth.com/mod/...
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: Other information you want to provide. Leave empty if none.
