modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Kikugie/elytra-trims/issues"
license = "LGPLv3"

[[mods]]
modId = "elytratrims_extensions"
version = "${version}"
displayName = "Elytra Trims Extensions"
authors = "KikuGie"
description = '''
Elytra Trims additions for other packs out there
'''
logoFile = "assets/elytratrims_extensions/icon.png"

[[dependencies.elytratrims_extensions]]
modId = "minecraft"
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "CLIENT"
